f =open("data.txt","a")
f.write("Appending new line\n")
f.close()
data=open("data.txt","r")
print(data.read())
data.close()

# f=open("data.txt","r")
f=open("sample.txt","r")
content=f.read()
print(content)
print(type(content))
data=f.readlines()
print(data)
f.close()
